apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-delete-tasks-api
  template:
    metadata:
      labels:
        app: todo-delete-tasks-api
    spec:
      containers:
      - name: todo-delete-tasks-api
        image: deployment.azurecr.io/deletetasktodomicroservice:16
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:trivvy.database.windows.net,1433;Database=trivvydb;Uid=trivvy;Pwd=Admin@123456;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
