apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-get-task-api
  labels:
    app: todo-get-task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-get-task-api
  template:
    metadata:
      labels:
        app: todo-get-task-api
    spec:
      containers:
      - name: todo-get-task-api
        image: deployment.azurecr.io/gettaskstodomicroservice:16
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:trivvy.database.windows.net,1433;Database=trivvydb;Uid=trivvy;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
